/**
 * Sichtbare UI-Texte (DE) – eine Stelle für Pitch & Wartung.
 * Keine API- oder Geschäftslogik.
 */
export const copy = {
  app: {
    brandTitle: "Internet Steuerung",
    brandSubtitle: "Schulzimmer VLAN Verwaltung",
    logout: "Abmelden",
  },
  login: {
    title: "Anmeldung",
    subtitle: "Internetzugang für Schulzimmer zentral steuern",
    usernameLabel: "Benutzername",
    passwordLabel: "Passwort",
    usernamePlaceholder: "",
    passwordPlaceholder: "••••••••",
    submit: "Anmelden",
    submitting: "Anmeldung läuft...",
    errorFallback: "Login fehlgeschlagen",
  },
  dashboard: {
    eyebrowOverview: "Übersicht",
    titleRooms: "Zimmersteuerung",
    lockAllRooms: "Alle sperren",
    unlockAllRooms: "Alle freigeben",
    toggleAllWorking: "Zimmer werden aktualisiert...",
    loading: "Lädt Daten...",
    loadError: "Fehler beim Laden der Daten",
    toggleError: "Fehler beim Umschalten",
    toggleAllError: "Fehler beim Umschalten aller Zimmer",
    selectRoomFirst: "Bitte zuerst ein Zimmer auswählen",
    whitelistNameMissing: "Bitte einen Namen für die Whitelist eingeben",
    whitelistUrlsMissing: "Bitte mindestens eine URL eingeben",
    whitelistCreateError: "Fehler beim Erstellen der Whitelist",
    whitelistUpdateError: "Fehler beim Aktualisieren der Whitelist",
    whitelistDeleteError: "Fehler beim Löschen",
    noSelection: "Keine Whitelist oder kein Zimmer ausgewählt",
    deleteConfirm: "Whitelist wirklich löschen?",
    modalEyebrow: "Whitelist",
    modalClose: "Schliessen",
    newWhitelist: "Neue Whitelist",
    hideForm: "Formular ausblenden",
    create: "Erstellen",
    emptyWhitelists: "Keine Whitelists für dieses Zimmer.",
    save: "Speichern",
    cancel: "Abbrechen",
    edit: "Bearbeiten",
    delete: "Löschen",
    newNamePlaceholder: "Name, z. B. Schulplattform",
    newUrlsPlaceholder: "Domains oder Hosts, eine Zeile pro Eintrag",
    editNamePlaceholder: "Whitelist-Name",
    editUrlsPlaceholder: "Hosts eine Zeile pro Eintrag",
  },
  toast: {
    toggleOn: "Internet aktiviert",
    toggleOff: "Internet gesperrt",
    toggleAllOn: "Internet in allen Zimmern aktiviert",
    toggleAllOff: "Internet in allen Zimmern gesperrt",
    whitelistCreated: "Whitelist erstellt",
    whitelistUpdated: "Whitelist aktualisiert",
    whitelistDeleted: "Whitelist gelöscht",
  },
  confirm: {
    toggleOffTitle: "Internet sperren",
    toggleOffBody: "verlieren sofort den Internetzugang.",
    toggleOnTitle: "Internet freigeben",
    toggleOnBody: "erhalten sofort Internetzugang.",
    toggleAllOffTitle: "Alle Zimmer sperren",
    toggleAllOffBody:
      "Alle Geräte in allen Zimmern verlieren sofort den Internetzugang.",
    toggleAllOnTitle: "Alle Zimmer freigeben",
    toggleAllOnBody:
      "Alle Geräte in allen Zimmern erhalten sofort Internetzugang.",
    deleteTitle: "Whitelist löschen",
    deleteBody: "Diese Whitelist wird unwiderruflich gelöscht.",
    ok: "Bestätigen",
    cancel: "Abbrechen",
  },
  audit: {
    eyebrow: "Verlauf",
    title: "Aktivitätsprotokoll",
    openButton: "Protokoll",
    close: "Schliessen",
    loading: "Lädt Protokoll...",
    loadError: "Fehler beim Laden des Protokolls",
    empty: "Keine Einträge vorhanden.",
    colTime: "Zeit",
    colUser: "Benutzer",
    colAction: "Aktion",
    colTarget: "Ziel",
    colStatus: "Status",
    ok: "OK",
    failed: "Fehler",
    actions: {
      login_success: "Login",
      login_failed: "Login gescheitert",
      internet_toggle: "Internet umgeschaltet",
      whitelist_create: "Whitelist erstellt",
      whitelist_update: "Whitelist bearbeitet",
      whitelist_delete: "Whitelist gelöscht",
      whitelist_toggle: "Whitelist an/aus",
    } as Record<string, string>,
  },
  room: {
    vlanPrefix: "VLAN",
    statusOn: "Internet aktiv",
    statusOff: "Internet gesperrt",
    lock: "Sperren",
    unlock: "Freigeben",
    manageWhitelist: "Whitelist verwalten",
    whitelistDirect: "Whitelist direkt erfassen",
  },
} as const;
