/**
 * Sichtbare UI-Texte (DE) – eine Stelle für Pitch & Wartung.
 * Keine API- oder Geschäftslogik.
 */
export const copy = {
  app: {
    brandTitle: 'Internet Steuerung',
    brandSubtitle: 'Schulzimmer VLAN Verwaltung',
    logout: 'Abmelden',
  },
  login: {
    title: 'Anmeldung',
    subtitle: 'Internetzugang für Schulzimmer zentral steuern',
    usernameLabel: 'Benutzername',
    passwordLabel: 'Passwort',
    usernamePlaceholder: '',
    passwordPlaceholder: '••••••••',
    submit: 'Anmelden',
    submitting: 'Anmeldung läuft...',
    errorFallback: 'Login fehlgeschlagen',
  },
  dashboard: {
    eyebrowOverview: 'Übersicht',
    titleRooms: 'Zimmersteuerung',
    loading: 'Lädt Daten...',
    loadError: 'Fehler beim Laden der Daten',
    toggleError: 'Fehler beim Umschalten',
    selectRoomFirst: 'Bitte zuerst ein Zimmer auswählen',
    whitelistNameMissing: 'Bitte einen Namen für die Whitelist eingeben',
    whitelistUrlsMissing: 'Bitte mindestens eine URL eingeben',
    whitelistCreateError: 'Fehler beim Erstellen der Whitelist',
    whitelistUpdateError: 'Fehler beim Aktualisieren der Whitelist',
    whitelistDeleteError: 'Fehler beim Löschen',
    noSelection: 'Keine Whitelist oder kein Zimmer ausgewählt',
    deleteConfirm: 'Whitelist wirklich löschen?',
    modalEyebrow: 'Whitelist',
    modalClose: 'Schliessen',
    newWhitelist: 'Neue Whitelist',
    hideForm: 'Formular ausblenden',
    create: 'Erstellen',
    emptyWhitelists: 'Keine Whitelists für dieses Zimmer.',
    save: 'Speichern',
    cancel: 'Abbrechen',
    edit: 'Bearbeiten',
    delete: 'Löschen',
    newNamePlaceholder: 'Name, z. B. Schulplattform',
    newUrlsPlaceholder: 'Domains oder Hosts, eine Zeile pro Eintrag',
    editNamePlaceholder: 'Whitelist-Name',
    editUrlsPlaceholder: 'Hosts eine Zeile pro Eintrag',
  },
  toast: {
    toggleOn: 'Internet aktiviert',
    toggleOff: 'Internet gesperrt',
    whitelistCreated: 'Whitelist erstellt',
    whitelistUpdated: 'Whitelist aktualisiert',
    whitelistDeleted: 'Whitelist gelöscht',
  },
  confirm: {
    toggleOffTitle: 'Internet sperren',
    toggleOffBody: 'verlieren sofort den Internetzugang.',
    toggleOnTitle: 'Internet freigeben',
    toggleOnBody: 'erhalten sofort Internetzugang.',
    deleteTitle: 'Whitelist löschen',
    deleteBody: 'Diese Whitelist wird unwiderruflich gelöscht.',
    ok: 'Bestätigen',
    cancel: 'Abbrechen',
  },
  room: {
    vlanPrefix: 'VLAN',
    statusOn: 'Internet aktiv',
    statusOff: 'Internet gesperrt',
    lock: 'Sperren',
    unlock: 'Freigeben',
    manageWhitelist: 'Whitelist verwalten',
    whitelistDirect: 'Whitelist direkt erfassen',
  },
} as const
